name: Tests

on:
  pull_request:
  push:
    branches: [master]
    tags: ['*']

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      
      - name: Run tests with reporting
        run: |
          docker compose -f docker-compose-tests.yaml up --force-recreate --no-deps --wait -d
          CONTAINER_ID=$(docker ps | grep mysql_ch_replicator-replicator | awk '{print $1;}')
          sudo docker exec -w /app/ -i $CONTAINER_ID \
            python3 -m pytest -x -v -s tests/ \
            --junitxml=test-results.xml \
            --html=test-report.html --self-contained-html
          # Copy test results from container to host
          sudo docker cp $CONTAINER_ID:/app/test-results.xml ./test-results.xml
          sudo docker cp $CONTAINER_ID:/app/test-report.html ./test-report.html

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results.xml
          comment_mode: always
          
      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            test-results.xml
            test-report.html